/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Emerald Hearth Design System
        'on-secondary-container': '#acb8b3',
        outline: '#879488',
        'surface-container-lowest': '#09100d',
        'on-error-container': '#ffdad6',
        'on-surface': '#dde4df',
        'on-tertiary-container': '#403500',
        'surface-container-low': '#161d1a',
        'inverse-primary': '#006d3d',
        'on-primary': '#00391d',
        'on-error': '#690005',
        'on-tertiary': '#3a3000',
        background: '#0e1512',
        'surface-container-high': '#242c28',
        'on-secondary-fixed': '#141e1b',
        'on-primary-fixed': '#00210f',
        'surface-bright': '#333b37',
        'tertiary-fixed': '#ffe16d',
        surface: '#0e1512',
        'primary-container': '#3cb371',
        'on-tertiary-fixed-variant': '#544600',
        primary: '#69dd96',
        'on-tertiary-fixed': '#221b00',
        'surface-container': '#1a211e',
        'on-background': '#dde4df',
        tertiary: '#e9c400',
        'primary-fixed': '#86fab0',
        'on-primary-container': '#003f21',
        'outline-variant': '#3e4a40',
        'surface-container-highest': '#2f3633',
        'surface-variant': '#2f3633',
        'primary-fixed-dim': '#69dd96',
        'on-primary-fixed-variant': '#00522d',
        'error-container': '#93000a',
        secondary: '#bec9c4',
        'on-surface-variant': '#bdcabd',
        error: '#ffb4ab',
        'surface-tint': '#69dd96',
        'secondary-fixed-dim': '#bec9c4',
        'tertiary-fixed-dim': '#e9c400',
        'secondary-fixed': '#dae5e0',
        'secondary-container': '#3e4945',
        'inverse-surface': '#dde4df',
        'on-secondary': '#28332f',
        'on-secondary-fixed-variant': '#3e4945',
        'inverse-on-surface': '#2b322e',
        'surface-dim': '#0e1512',
        'tertiary-container': '#ba9c00',
        // Dark/light mode aliases for onboarding
        'background-light': '#f8faf9',
        'background-dark': '#0e1512',
        'surface-dark': '#1a211e',
        'text-primary-dark': '#dde4df',
        'text-secondary-dark': '#bdcabd',
        'border-dark': '#3e4a40',
      },
      fontFamily: {
        headline: ['Epilogue'],
        body: ['Be Vietnam Pro'],
        label: ['Manrope'],
        display: ['Plus Jakarta Sans', 'sans-serif'], // Keep existing for compatibility
      },
      height: {
        card: '340px',
        'card-image': '220px',
        nav: '64px',
        header: '48px',
      },
      spacing: {
        'nav-clearance': '160px',
        'safe-bottom': '96px',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        '2xl': '2rem', // Keep existing
        '3xl': '3rem', // Keep existing
        full: '9999px',
      },
    },
  },
  plugins: [],
}
