name = "meal-swiper"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "MEAL_PLANS"
id = "324e90f7cc804791afdcd3a32af4bcbe"
